services:
  ytchat:
    build:
      context: ./Code
      dockerfile: Dockerfile
    container_name: ytchat
    network_mode: "host"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./Code:/workdir
    
    ports:
      - "8501:8501"
    
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    dns:
      - 8.8.8.8
      - 8.8.4.4
